server:
  port: 8899
spring:
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/me
  headers:
    frame: false
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO